// STUB, pre-staged by Wave 1. Agent C (Cookbook Browser) owns the real implementation:
// group/filter entries by real-life goal, add search, and a copy-able starter prompt per
// entry with a working copy button. Data comes from the shared loader (content/cookbook.json,
// generated by scripts/gen-cookbook.mjs).
import { loadCookbook } from '../content/cookbook';

export default function Cookbook() {
  const entries = loadCookbook();
  return (
    <div className="mx-auto max-w-3xl p-6">
      <h1 className="mb-4 text-3xl">What Can AI Actually Do?</h1>
      <p className="mb-6 text-ink-soft">Real uses by goal, each with a prompt you can copy.</p>
      <ul className="space-y-3">
        {entries.map((e, i) => (
          <li key={i} className="panel p-4">
            <p className="text-ink-faint">{e.goal}</p>
            <p className="font-display">{e.title}</p>
            <code className="text-sm">{e.prompt}</code>
          </li>
        ))}
      </ul>
    </div>
  );
}
